"use client";
import type { Metadata } from "next";
import { Geist, Geist_Mono, Montserrat } from "next/font/google";
import "./globals.css";
import {
  SidebarInset,
  SidebarProvider,
  SidebarTrigger,
} from "@/components/ui/sidebar";
import AppSidebar from "@/components/app-sidebar";
import Header from "@/components/Header";
import { AuthProvider } from "./context/AuthContext";
import { usePathname } from "next/navigation";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const pagesWithoutSidebar = ["/login", "/register", "/forgot-password"];
  const pathname = usePathname();
  const shouldShowSidebar = !pagesWithoutSidebar.includes(pathname);

  return (
    <html lang="en">
      <AuthProvider>
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
          <SidebarProvider>
            {shouldShowSidebar && <AppSidebar />}
            <SidebarInset>
              {shouldShowSidebar && (
                <SidebarTrigger className="text-[#0A4F45]" />
              )}
              <Header showLogout={shouldShowSidebar} />
              {children}
            </SidebarInset>
          </SidebarProvider>
        </body>
      </AuthProvider>
    </html>
  );
}
